[package]
name = "rustfearlessstructured"
version = "0.1.0"
edition = "2018"

[dependencies]
async-scoped = { version = "0.7.0", features = ["use-async-std"] }
async-std = { version = "1.6.3", features = ["attributes"]  }
